sudo: required
dist: bionic
language: generic
services:
  - docker
arch:
  - arm64

env:
  - ROS_DISTRO=kinetic
  - ROS_DISTRO=melodic
  - ROS_DISTRO=melodic-py3
  - ROS_DISTRO=noetic

before_script:
  - docker pull sfalexrog/multipack:${ROS_DISTRO} || true

script:
  - pushd docker
  - pushd ${ROS_DISTRO}-builder
  - docker build --rm --tag=sfalexrog/multipack:${ROS_DISTRO} .
  - popd
  - popd
  - pushd tests
  - ./run_tests.sh
  - popd

after_success:
  - >
    if [ "${TRAVIS_BRANCH}" = "master" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      docker push "sfalexrog/multipack:${ROS_DISTRO}"
    fi
