sudo: required
language: generic
services:
  - docker

before_script:
  - docker pull sfalexrog/qemu-register:v4.1.0
  - docker run --rm --privileged sfalexrog/qemu-register:v4.1.0

script:
  - pushd docker
  - ./build.sh
  - popd
