sudo: required
dist: bionic
language: generic
services:
  - docker

env:
  - ROS_DISTRO=kinetic
  - ROS_DISTRO=melodic

before_script:
  - docker run --rm --privileged sfalexrog/qemu-register:v4.1.0

script:
  - pushd docker
  - pushd ${ROS_DISTRO}-builder
  - docker build --rm --tag=sfalexrog/multipack:${ROS_DISTRO} .
  - popd
  - popd
  - pushd tests
  - ./run_tests.sh
  - popd

after_script:
  - >
    if [ "${TRAVIS_BRANCH}" == "master" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      docker push "sfalexrog/multipack:${ROS_DISTRO}"
    fi
