sudo: required
dist: bionic
language: generic
services:
  - docker

script:
  - pushd docker
  - ./build.sh
  - popd
  - pushd tests
  - ./run_tests.sh
  - popd

after_script:
  - >
    if [ "${TRAVIS_BRANCH}" == "master" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      docker push "sfalexrog/multipack:melodic"
    fi
